### ISSUE TITLE
sec_score가 역할을 벗어난 일까지 수행중임

### ISSUE THREAD

**Issue by Nevaland** [Maple-Factory/MapleFi#32]
https://github.com/Maple-Factory/MapleFi/blob/de70b85b6b082c45c5b00104c6aa2d83fd08474f/app/src/main/java/com/example/maplefi/util/SecurityEstimater.java#L20

sec_score는 보안 점수(총합)만을 가지게 하고, 항목 별 점수는 따로 변수를 만들어 관리하도록 변경

**Comment by PororiLi** [comment]
secScore과 secScores[5] 로  나눠 관리하도록 수정함
